IMAGE_FILE_EXTENSIONS = ['png', 'jpeg', 'jpg', 'gif']

IMAGE_SIZE1 = 224
IMAGE_SIZE2 = (IMAGE_SIZE1, IMAGE_SIZE1)
IMAGE_SIZE3 = (IMAGE_SIZE1, IMAGE_SIZE1, 3)
IMAGE_SIZE4 = (1, IMAGE_SIZE1, IMAGE_SIZE1, 3)

IMAGE_DATAFRAME_COLS = ('Filepath', 'Classes', 'Label')
DATA_PATH = 'data'
CLASSES = ['OK', 'RNG', 'LNG', 'LRNG']